### ISSUE TITLE
Clone App Error

### ISSUE THREAD

**Issue by rhester51912** [jeremiahcurrier/clone-ticket#4] opened 2015-04-07 16:43 UTC
Hi Jerry -

I'm having issues with the clone app.  I'm getting the following Javascript error (below) when I try to clone a ticket.

Can you please advise! 

Also, I'm new to GitHub so will you please email me at rhester@cpf.com with your reply.  

Thanks! 

![clone_app_error](https://cloud.githubusercontent.com/assets/11839201/7028373/50a05172-dd0a-11e4-81f1-901956c0e50b.png)

**Comment by jeremiahcurrier** [comment] 2015-05-19 20:33
Hey @rhester51912 - I can't reproduce the errors you're reporting - can you provide reproduction steps? 

Here's what I'm seeing - using a creation limit of 20 tickets as an example: 

![](http://g.recordit.co/SgkJ8ApCRQ.gif)

**Comment by rhester51912** [comment] 2015-05-26 19:41
Thanks Jeremiah.

Where do the clone tickets go?  Sometimes I get an error message and just
now it appeared to work, but I can't find the duplicated ticket.

Thanks!

Ryan Hester

_Manager, Customer Support_

_Clean Power Finance_

Check out the _new_ CPF Resource Center
http://resources.cleanpowerfinance.com/ for training and support.
-  (You will be prompted to log in to CPF Tools to access) *

T | 866.525.2123 x 2
F | 415.354.3221
cleanpowerfinance.com http://www.cleanpowerfinance.com/

This email and its attachments may contain private and confidential
material, and therefore
should not be reviewed, copied or distributed by others without permission.
If you are not
the intended recipient, please alert the sender immediately and delete the
original.

**Comment by clong-** [comment] 2015-06-15 16:50
Hey folks,

The issue we're looking at here is due to the way the app attempts to handle CCs. @jeremiahcurrier, you didn't test with CCs on your ticket, which is why you didn't see the error. ;)

Line 42 in app.js uses `cc.email()` for the `collaborator_ids` array, however the endpoint expects integer IDs in that array. This is easily fixed by changing that line to use `cc.id()` instead. Tested with ZAT, and it works like a charm!

-Creighton

**Closed as completed** 2015-06-17 18:29 UTC
